


export const metadata = {
    title: 'Blog Lists',
    description: 'Generated by Dinh Tuan Tinh',
}

export default function BlogLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
        </>
    )
}
